### ISSUE TITLE
Fix typo on Readme

### ISSUE THREAD

**Issue by aurelmegn** [Godmind-BM/sitemgr#1]
The command `pip install -r requierements.txt` is misspelled

**Comment by aurelmegn** [comment]
@Godmind-BM 
Il faudrait améliorer la description de l'utilisation.
Actuellement les commandes qui sont dans le Readme ne semblent être suffisante pour démarrer.
Par exemple j'ai l'erreur ci-dessous avec la commande 
`python sitemgr.py add google.com`.
```
Traceback (most recent call last):
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sitemgr.py", line 1, in <module>
    from main.src.ui.commands import site_manager
  File "/home/aurel/Projects/aristide/sitemgr/main/src/ui/commands.py", line 4, in <module>
    from main.src.backend.handlers import add_handler, rm_handler, update_handler
  File "/home/aurel/Projects/aristide/sitemgr/main/src/backend/handlers.py", line 8, in <module>
    from main.src.backend.model import Site, engine
  File "/home/aurel/Projects/aristide/sitemgr/main/src/backend/model.py", line 40, in <module>
    Base.metadata.create_all(engine)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4554, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2094, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2086, in _optional_conn_ctx_manager
    with self._contextual_connect() as conn:
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/aurel/Projects/aristide/sitemgr/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```
D'un autre coté 
```
./sitemgr.py add google.com
Failed to execute process './sitemgr.py'. Reason:
exec: Exec format error
The file './sitemgr.py' is marked as an executable but could not be run by the operating system.
```
